### PR TITLE
To-Do List App 

### PR DESCRIPTION
**Pull request by akjain1509**
to do list added with delete task feature

Screen 1 (Main Screen):
Display a list of tasks with checkboxes to mark them as completed.
Button to add a new task.

Screen 2 (Add Task):
Input field to add a new task.
Button to save the task.

Directory: /src/screens/ToDoList

### CODE REVIEW

**Comment by Hemu21** [comment]
@akjain1509  can you please tell the node version you used.

**Comment by akjain1509** [comment]
> @akjain1509 can you please tell the node version you used.

v18.17.0

**Comment by Hemu21** [comment]
@akjain1509 Thank you

**Review by smilewithkhushi — APPROVED** [review]
Clean and readable code! The given functionalities have been fulfilled

**Comment by smilewithkhushi** [comment]
Merged! Great work!
make sure to provide the screenshots of the output in the future PRs for faster approval.

**Comment by akjain1509** [comment]
HI Khushi,
Hope you are doing well. Thank you so much and I will keep in mind to
attach snapshots.
Can you please assign me another task? I have commented on various issues
too.
Please assign me a QR generator task. I have commented on that

Thanks & Regards
Ankita Jain

**Pull request merged**
