### PR TITLE
Movie Finder and Color Generator

### PR DESCRIPTION
**Pull request by Manaswini123456**
This PR adds a new screen to the app for searching movies and retrieving their data using the OMDb API. The OMDb API is a popular choice for accessing movie and television information, and integrating it into our app enhances the user experience by allowing them to search for movies easily.

Changes Made
1. Added a new screen for searching movies (MovieFinder.js).
2. Integrated the OMDb API to fetch movie data based on user search queries.
3. Styled the search screen and added UI components for input and search button.
4. Handled loading and error states while fetching movie data.
5. Displayed search results in a list with movie titles, posters, and additional details.

HomeScreen
Search Screen

Additional Notes
1. Any feedback or suggestions for further improvements are welcome.

IMPORTANT INFORMATION
 
Some people have mentioned of getting error of the below sort:
image

What they can do?
Ans.  In order to tackle with that package.json had to be changed and then 'npm i' had to be done. The major change was the deletion of the fresco part of the package.json and then the inclusion of 'react-native-fast-image'

### CODE REVIEW

**Comment by Manaswini123456** [comment]
@smilewithkhushi kindly merge this PR

**Review by smilewithkhushi — COMMENTED** [review]
Great work! 
Make sure to add valid and descriptive comments in your code to explain the functionality in simpler way.

**Comment by smilewithkhushi** [comment]
need to review some conflicting files! will merge this PR in a day or two (a lil occupied with end sems)
i hope you'll understand! Great work btw <3

**Comment by Manaswini123456** [comment]
@smilewithkhushi I have worked upon the issue and attaching the screenshots regarding the same.

WhatsApp Image 2024-05-14 at 01 31 15_2c9f1b59

COLOR GENERATOR:
WhatsApp Image 2024-05-14 at 01 31 15_5a1f192b

Changes Made: 
1. Added a folder called HexColorGenerator 
2. Within the folder added HexColorGeneratorScreen.js to generate random colors.
3. Using Math.random() and other function tried to generate random colors with showing their Hex Code, RGB and RGBA codes

**Review by smilewithkhushi — APPROVED** [review]
Her Color generator application has clean, understandable and functional code! Good work.

**Comment by Manaswini123456** [comment]
@smilewithkhushi Thank you so much.

**Pull request merged**
