### PR TITLE
AnimeFinder has been added

### PR DESCRIPTION
**Pull request by Sypher0Dronzer**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
#60 
## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image
image
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

**Can I get a level 3 if this project is worth that  . Thank you**
Please review this @smilewithkhushi

### CODE REVIEW

**Review by smilewithkhushi — CHANGES_REQUESTED** [review]
the  UI can be improved to meet the level 2 criteria. 
else, it'll be labelled under level 1. also, add comments in your code.

**Comment by Sypher0Dronzer** [comment]
okay 
I willupdate the Ui and add comments

**Comment by Sypher0Dronzer** [comment]
Can you review now @smilewithkhushi 

image
image
image

**Review by smilewithkhushi — APPROVED** [review]
approved the changes

**Pull request merged**
