### PR TITLE
completed RecipeFinder App

### PR DESCRIPTION
**Pull request by saikrishna823**
Completed the application.Implemented all the required features.Used drawer naviagtion to show favourites recipes.

### CODE REVIEW

**Comment by saikrishna823** [comment]
@smilewithkhushi , kindly check this Pull request.Let me know any issues.

**Review by smilewithkhushi — CHANGES_REQUESTED** [review]
the code is nicely written but it has ruined the directory structure which was planned  while keeping in mind the mass contributions.
Kindly segregate the components, context and other directories. you should keep all the screens under scr/screens/RecipeFinder itself.
For the components, go to src/components/RecipeFinder and then add your dedicated components here.  Also, try to write comments in your code.

**Comment by saikrishna823** [comment]
Oka,I will make required changes and let you know.

**Comment by saikrishna823** [comment]
@smilewithkhushi ,I kept all the screens of RecipeFinder in src/screens/RecipeFinder only,and components also in the same manner.Could you please verify it again.

**Review by saikrishna823 — COMMENTED** [review]
addede comments to all screens

**Comment by saikrishna823** [comment]
I maintained directory structure,I created separate folder for RecipeFinder,i that I created folders like components,screens,api,context.so that everyone will understand clearly.I made all the folders inside the RecipeFinder only.It doesn't cause any problem to directory structure.Please merge this pull request.

**Review by smilewithkhushi — APPROVED** [review]
👍🏻

**Pull request merged**
